apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp

spec: 
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: 
    metadata: 
      labels: #service가 라벨로 찾는다.
        app: webapp

    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata: 
  name: queue
  labels:
    app: queue

spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
