# Storage for mongo-pvc
# What do we want?
apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

# How do we implement?
apiVersion: v1
kind: persistentVolume
metadata:
  name: local-storage
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/mnt/some/new/directory/blahblah/"
    type: DirectoryOrCreate
    