apiVersion: v1
kind: Service
metadata: 
  name: fleetman-webapp

spec:
# 포트포워딩하여 네트워크 엔드포인트를 제공
  ports:
  - name: http
    port: 80
    nodePort: 30080 #30000보다 반드시커야한다고함

  selector: 
    app: webapp
    release: 0-5

  type: NodePort 
    